[workspace]
members = ["pathogen", "pathogen_macros", "tests"]
resolver = "2"

[workspace.package]
authors = ["Red Badger Consulting Limited"]
edition = "2021"
rust-version = "1.70.0"
repository = "https://github.com/redbadger/pathogen/"
